# Generated by Django 4.2.3 on 2023-08-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
