# Generated by Django 4.2.3 on 2023-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_blog', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='post_counter',
            field=models.IntegerField(default=0),
        ),
    ]
